// Licensed under the Apache License, Version 2.0 (the “License”); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an “AS IS” BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

import CliUi from './CliUi'
import {
  TASK_STARTED,
  TASK_STOPPED,
  TASK_UPDATED,
} from '../events'

/**
 * Updates the UI according to events generated by the system.
 *
 * @param store
 * Store that holds the CLI’s state.
 * @param eventBus
 * Communication bus used to receive events.
 */
export function setUpUi(store, eventBus) {
  const CLI_UI = new CliUi

  eventBus.subscribe(event => {
    let {type, payload} = event

    switch (type) {
      case TASK_STARTED:
        CLI_UI.addSpinner(payload)
        break

      case TASK_STOPPED:
        CLI_UI.removeSpinner(payload)
        break

      case TASK_UPDATED:
        CLI_UI.updateSpinner(payload)
        break
    }
  })

  CLI_UI.start()
}
